baseUri: https://sparql.crssnky.xyz/imasrdf/
generation:
  - query: |
      PREFIX schema: <http://schema.org/>
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX imas: <https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>
      SELECT  ?m (group_concat(?s;separator=",,,,,")as ?u)
      WHERE {
        ?s rdf:type imas:Clothes;
           imas:Whose ?m.
      }group by (?m) order by ?m ?s
    template: .github/Clothes_Own.rdf.template
    output: RDFs/Clothes_Own.rdf
suppressPath: .github/rdflint-suppress.yml
