version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: run rdflint
        command: |
          RDFLINT_VERSION=0.0.7
          wget https://jitpack.io/com/github/imas/rdflint/$RDFLINT_VERSION/rdflint-$RDFLINT_VERSION-all.jar
          for f in Clothes_Own Unit_memberOf; do
            java -jar rdflint-$RDFLINT_VERSION-all.jar -config .circleci/$f.yml
          done
          java -jar rdflint-$RDFLINT_VERSION-all.jar -config .circleci/rdflint-config.yml
